### PR TITLE
Feat: Repo fetching issue6

### LINKED ISSUE #6: feat: Fetch updates from repository
* implement fetchRepoUpdates() in CIWorker.java
* providing the functionality of step 3) in the Outline architecture of [CI server](https://trello-attachments.s3.amazonaws.com/5c4ee33443b25f6db0785109/5c532662e8ae4879f533081b/1a6e9e57a34aca6732202929f0f17801/image.png)

### PR DESCRIPTION
**Pull request by fredrikfloven**
This PR implements a method for cloning a repo based on a branch commit hash as well as a method for removing data. A test is added for the data removal method.
Closes #6 if merged
[Trello card](https://trello.com/c/L8tQW9vN)

### CODE REVIEW

**Comment by lilfelix** [comment]
It seems tricky to test the cloning of git repos. I don't think there's any point in us testing that JGit works as specified by their API. `cloneFromSha` consists mostly of calls to the JGit API, so what is left to test? Also, will we be needing `cloneFromBranch`?

We can test that a folder is removed by calling `deleteData()` though:
- Arrange: Create an empty folder e.g `test_folder`
- Act: Call `deleteData("test_folder")
- Assert: `assertTrue(Files.notExists(path_to_test_folder))`

What do you think?

**Comment by fredrikfloven** [comment]
> It seems tricky to test the cloning of git repos. I don't think there's any point in us testing that JGit works as specified by their API. `cloneFromSha` consists mostly of calls to the JGit API, so what is left to test? Also, will we be needing `cloneFromBranch`?
> 
> We can test that a folder is removed by calling `deleteData()` though:
> 
> * Arrange: Create an empty folder e.g `test_folder`
> * Act: Call `deleteData("test_folder")
> * Assert: `assertTrue(Files.notExists(path_to_test_folder))`
> 
> What do you think?

I agree that testing cloning of repos are difficult. 
I could add that given an empty string as hash, it clones the master branch? That is testable as long as the repo is live. But the actual data would differ over time, so maybe it could test on the repo being created and not being empty I suppose? Opinions?

cloneFromBranch was the initial method, but I don't think we need it either, so I will remove it.

Adding tests for deleteData sounds good, I'll add that.

**Comment by lilfelix** [comment]
I'm not sure we need to test that `master` is cloned when `sha=""` unless it's a feature we plan on using. Testing that feature would also require cloning the entire repo, in order to assert that `master` is in fact what is cloned when `sha=""`.

The issue of testing that `cloneFromSha` works as intended in a more general sense remains. 

Apart from the unit test for `deleteData`, I think we can skip unit testing of `cloneFromSha` and instead open up an issue for end-to-end testing that we can do later. 
When the CI server is nearly finished we can write end-to-end tests ensuring that the repo is cloned properly etc.

**Comment by fredrikfloven** [comment]
> I'm not sure we need to test that `master` is cloned when `sha=""` unless it's a feature we plan on using. Testing that feature would also require cloning the entire repo (not suitable for a unit test), in order to assert that `master` is in fact what is cloned when `sha=""`.
> 
> The issue of testing that `cloneFromSha` works as intended in a more general sense remains.
> 
> Apart from the unit test for `deleteData`, I think we can skip unit testing of `cloneFromSha` and instead open up an issue (**edit: #17 is open now**) for end-to-end testing that we can do later.
> When the CI server is nearly finished we can write end-to-end tests ensuring that the repo is cloned properly etc.

Yeah, I realised that an empty string shouldn't clone anything.
I'll create a test for deleteData and we'll leave the test for cloning for the end.

**Pull request merged**
